alias: Ferme le vélux de Lenaïc s'il fait trop froid dehors
trigger:
  - platform: template
    value_template: '{{ (states.sensor.sensative_strips_comfort_temperature.state
    | float) > (states.sensor.netatmo_terrasse_temperature.state | float) }}'
condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.sensative_strips_comfort_temperature
  - condition: state
    entity_id: cover.velux_lenaic
    state: open
action:
  - service: script.turn_on
    data:
      entity_id: script.close_velux_lenaic
