- alias: Set Qubino to Comfort
  trigger:
    platform: state
    entity_id: input_select.qubino
    to: 'Confort'
  action:
    service: light.turn_on
    entity_id: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level
    data:
      brightness: 100
  id: 322e1962112842dab4defab990286212
- alias: Set Qubino to Eco
  trigger:
    platform: state
    entity_id: input_select.qubino
    to: 'Eco'
  action:
    service: light.turn_on
    entity_id: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level
    data:
      brightness: 60
  id: 8397b8f4cccd4dca90996ba38e760ba4
- alias: Set Qubino to Anti Freeze
  trigger:
    platform: state
    entity_id: input_select.qubino
    to: 'Hors Gel'
  action:
    service: light.turn_on
    entity_id: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level
    data:
      brightness: 30
  id: 04d972cb89ba4fce96b669c95e4e4e48
- alias: Set Qubino to Stop
  trigger:
    platform: state
    entity_id: input_select.qubino
    to: 'Eteint'
  action:
    service: light.turn_on
    entity_id: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level
    data:
      brightness: 0
  id: 9d3e9fcf237449eaac1bd771e1509b0b

########################################################################################    

- alias: Scan for faces when motion detected outside
  trigger:
  - platform: state
    entity_id: binary_sensor.camterrasse_outdoor_human
    to: 'on'
  action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.face_counter_terrasse

########################################################################################    

- alias: Scan for faces when motion detected inside
  trigger:
  - platform: state
    entity_id: binary_sensor.camsalon_motion
    to: 'on'
  action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.face_counter_salon

########################################################################################    

- id: Movement Detected
  alias: Movement Detectedk
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: netatmo_webhook
  action:
  - service: notify.google_push
    data_template:
      message: "{{ trigger.json | tojson }}"
  - service: mqtt.publish
    data_template:
      topic: 'netatmo/update'
      retain: true
      payload_template: >
        {{ trigger.json | tojson }}
    
########################################################################################    

- alias: Test ifttt Webhook
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: ifttt_button
  action:
  - service: notify.google_push
    data_template:
      message: "{{ trigger.json | tojson }}"
    
########################################################################################    

- id: Movement Detected Inside
  alias: mouvement détecté dehors
  trigger:
  - event_data: {}
    event_type: netatmo_movement
    platform: event
  - event_data: {}
    event_type: netatmo_human
    platform: event
  - event_data: {}
    event_type: netatmo_animal
    platform: event
  - event_data: {}
    event_type: netatmo_vehicle
    platform: event
  - event_data: {}
    event_type: netatmo_other
    platform: event
  action:
  - service: notify.google_push_pixel_2
    data_template:
      message: mouvement détecté {{ trigger.event.data.event.message }}
  - service: camera.snapshot
    data:
      entity_id: camera.camterrasse
      filename: 'www/camera/terrasse-{{ now().strftime("%Y-%m-%d-%H%M%S") }}.jpg'
  - service: camera.snapshot
    data:
      entity_id: camera.camterrasse
      filename: 'www/camera/terrasse-latest.jpg'
    
########################################################################################    
    
- id: Nettoie les appareils connus
  alias: Nettoie les appareils connus
  trigger:
  - platform: homeassistant
    event: start
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: shell_command.clean_knowndevices

########################################################################################    

- id: Ferme les volets de velux la nuit
  alias: Ferme les volets de velux la nuit
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  action:
  - service: script.turn_on
    data:
      entity_id: script.secure_close_volet_lenaic
  - service: script.turn_on
    data:
      entity_id: script.secure_close_volet_palier
  - service: notify.google_push_pixel_2
    data:
      message: Le soleil est couché, je ferme les volets

########################################################################################    

- id: Ferme les velux en cas de pluie
  alias: Ferme les velux en cas de pluie
  trigger:
  - above: '0.1'
    entity_id: sensor.netatmo_pluie_jardin_rain
    platform: numeric_state
  - entity_id: weather.ti_ar_kaerell
    platform: state
    to: rainy
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: cover.velux_palier
      state: open
    - condition: state
      entity_id: cover.velux_lenaic
      state: open
  action:
  - service: cover.close_cover
    data_template:
      entity.id: >
        {% if is_state('cover.velux_palier','open') %}
          cover.velux_palier
        {% endif %}
  - service: cover.close_cover
    data_template:
      entity.id: >
        {% if is_state('cover.velux_lenaic','open') %}
          cover.velux_palier
        {% endif %}
  - service: notify.google_push_pixel_2
    data:
      message: il pleut, je ferme les velux

########################################################################################    

- id: Ferme tout sur le palier s il fait trop chaud dehors
  alias: Ferme tout sur le palier s'il fait trop chaud dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.tdeg_parents.state | float) < (states.sensor.netatmo_terrasse_temperature.state
      | float) }}'
  condition:
  - above: '22'
    condition: numeric_state
    entity_id: sensor.tdeg_parents
  - condition: or
    conditions:
    - condition: state
      entity_id: cover.volet_palier
      state: open
    - condition: state
      entity_id: cover.velux_palier
      state: open
  action:
  - service: script.turn_on
    data:
      entity_id: script.close_both_palier
  - service: notify.google_push_pixel_2
    data:
      message: il fait trop chaud dehors, je ferme le palier !

########################################################################################    

- id: Ferme tout chez Lenaïc s il fait trop chaud dehors
  alias: Ferme tout chez Lenaïc s'il fait trop chaud dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.sensative_strips_comfort_temperature.state
      | float) < (states.sensor.netatmo_terrasse_temperature.state | float) }}'
  condition:
  - above: '22'
    condition: numeric_state
    entity_id: sensor.sensative_strips_comfort_temperature
  - condition: or
    conditions:
    - condition: state
      entity_id: cover.volet_lenaic
      state: open
    - condition: state
      entity_id: cover.velux_lenaic
      state: open
  action:
  - service: script.turn_on
    data:
      entity_id: script.close_both_lenaic
  - service: notify.google_push_pixel_2
    data:
      message: il fait trop chaud dehors, je ferme chez Lenaïc !

########################################################################################    

- id: Ouvre le vélux du palier s il fait assez frais dehors
  alias: Ouvre le vélux du palier s'il fait assez frais dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.tdeg_parents.state | float) > (states.sensor.netatmo_terrasse_temperature.state
      | float) }}'
  condition:
  - above: '22'
    condition: numeric_state
    entity_id: sensor.tdeg_parents
  - below: '0.1'
    condition: numeric_state
    entity_id: sensor.netatmo_pluie_jardin_rain
  - condition: template
    value_template: "{{ not is_state('weather.ti_ar_kaerell','rainy') }}"
  action:
  - service: notify.google_push
    data:
      message: Il fait assez frais dehors, j'ouvre le vélux du palier
  - service: script.turn_on
    data:
      entity_id: script.open_velux_palier

########################################################################################    

- id: Ouvre le vélux de Lenaïc s il fait assez frais dehors
  alias: Ouvre le vélux de Lenaïc s'il fait assez frais dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.sensative_strips_comfort_temperature.state
      | float) > (states.sensor.netatmo_terrasse_temperature.state | float) }}'
  condition:
  - above: '22'
    condition: numeric_state
    entity_id: sensor.sensative_strips_comfort_temperature
  - below: '0.1'
    condition: numeric_state
    entity_id: sensor.netatmo_pluie_jardin_rain
  - condition: template
    value_template: "{{ not is_state('weather.ti_ar_kaerell','rainy') }}"
  action:
  - service: notify.google_push
    data:
      message: Il fait assez frais dehors, j'ouvre le vélux de Lenaïc
  - service: script.turn_on
    data:
      entity_id: script.open_velux_lenaic

########################################################################################    

- id: Ferme le vélux du palier s il fait trop froid dehors
  alias: Ferme le vélux du palier  s'il fait trop froid dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.tdeg_parents.state | float) > (states.sensor.netatmo_terrasse_temperature.state
      | float) }}'
  condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.tdeg_parents
  - condition: state
    entity_id: cover.velux_palier
    state: open
  action:
  - service: notify.google_push
    data:
      message: Il fait trop froid dehors, je ferme le vélux du palier
  - service: script.turn_on
    data:
      entity.id: script.close_velux_palier

########################################################################################    

- id: Ferme le vélux de Lenaïc s il fait trop froid dehors
  alias: Ferme le vélux de Lenaïc s'il fait trop froid dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.sensative_strips_comfort_temperature.state
      | float) > (states.sensor.netatmo_terrasse_temperature.state | float) }}'
  condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.sensative_strips_comfort_temperature
  - condition: state
    entity_id: cover.velux_lenaic
    state: open
  action:
  - service: notify.google_push
    data:
      message: Il fait trop froid dehors, je ferme le vélux de Lenaïc
  - service: script.turn_on
    data:
      entity.id: script.close_velux_lenaic
