# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  customize: !include includes/customize.yaml
  whitelist_external_dirs:
    - /config
    - /config/www/
    - /config/www/camera
    - /config/www/deepstack/Salon
    - /config/www/deepstack/Terrasse
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 172.30.32.1
      allow_bypass_login: true
    - type: homeassistant

cloud:
default_config:
map:
person:
stream:
sun:

automation:       !include_dir_list includes/automations
binary_sensor:    !include_dir_list includes/binary_sensors
camera:           !include_dir_list includes/cameras
climate:          !include_dir_list includes/climates
device_tracker:   !include_dir_list includes/device_trackers
image_processing: !include_dir_list includes/image_processings
media_player:     !include_dir_list includes/media_players
notify:           !include_dir_list includes/notifies
remote:           !include_dir_list includes/remotes
sensor:           !include_dir_list includes/sensors

input_boolean:    !include_dir_named includes/input_booleans
input_select:     !include_dir_named includes/input_selects
panel_iframe:     !include_dir_named includes/panel_iframes

downloader:       !include includes/dowloader.yaml
group:            !include includes/groups.yaml
google:           !include includes/google.yaml
google_assistant: !include includes/google_assistant.yaml
hacs:             !include includes/hacs.yaml
http:             !include includes/http.yaml
life360:          !include includes/life360.yaml
logger:           !include includes/logger.yaml
lovelace:         !include includes/lovelace.yaml
mqtt:             !include includes/mqtt.yaml
netatmo:          !include includes/netatmo.yaml
proximity:        !include includes/proximity.yaml
script:           !include includes/scripts.yaml
shell_command:    !include includes/shell_command.yaml
somfy:            !include includes/somfy.yaml
switch:           !include includes/switches.yaml
tahoma:           !include includes/tahoma.yaml
tts:              !include includes/tts.yaml
weather:          !include includes/weather.yaml
zone:             !include includes/zones.yaml
zwave:            !include includes/zwave.yaml
