resources:
- type: module
  url: /local/community/mini-graph-card-bundle.js
- type: module
  url: /local/community/custom-weather-card-chart.js
- type: js
  url: /local/community/vertical-stack-in-card.js?v=0.1.3
- type: js
  url: /local/community/lovelace-home-feed-card/home-feed-card.js
- url: /community_plugin/atomic_calendar/atomic_calendar.js
  type: module
    
title: Ti Ar Kaerell
views:
# Onglet principal
- path: home
  title: Accueil
  cards: !include_dir_list ui/accueil

# Onglet Salon
- title: Rez de Chaussée
  path: rez
  cards: !include_dir_list ui/rez

# Onglet Etage        
- path: etage
  title: Etage
  cards: !include_dir_list ui/etage

# Onglet configuration
- path: conf
  title: Configuration
  cards: !include_dir_list ui/conf

# Onglet snapshots
- path: snapshots
  title: Snapshots
  cards: !include_dir_list ui/snapshots

# Onglet deepstack
- path: deepstack
  title: Deepstack
  cards: !include_dir_list ui/deepstack