alias: Ferme tout sur le palier s'il fait trop chaud dehors
trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_palier_temperature.state | float) < (states.sensor.netatmo_terrasse_temperature.state
    | float) }}'
condition:
  - above: '21'
    condition: numeric_state
    entity_id: sensor.netatmo_palier_temperature
  - condition: or
    conditions:
      - condition: state
        entity_id: cover.volet_palier
        state: open
      - condition: state
        entity_id: cover.velux_palier
        state: open
action:
  - service: script.turn_on
    data:
      entity_id: script.close_both_palier
