alias: Ferme le vélux du palier s'il fait trop froid dehors
trigger:
  - platform: template
    value_template: '{{ (states.sensor.tdeg_parents.state | float) > (states.sensor.netatmo_terrasse_temperature.state
    | float) }}'
condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.tdeg_parents
  - condition: state
    entity_id: cover.velux_palier
    state: open
action:
  - service: script.turn_on
    data:
      entity_id: script.close_velux_palier
