alias: La maison n'est pas vide
trigger:
  - platform: numeric_state
    entity_id: proximity.home1
    below: 2000
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: proximity.home2
    below: 2000
    for:
      minutes: 5
#   - condition: state
#     entity_id: lock.ti_ar_kaerell
#     state: unlocked
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radiateur_parents
      temperature: 21
  - service: climate.set_temperature
     data:
       entity_id: climate.radiateur_bureau
       temperature: 21
  - service: climate.set_temperature
     data:
       entity_id: climate.radiateur_salon
       temperature: 21
