alias: La maison est vide
trigger:
  - platform: state
    entity_id: sensor.home
    to: empty
# condition:
#   - condition: state
#     entity_id: lock.ti_ar_kaerell
#     state: unlocked
action:
  - service: lock.lock
    data:
      entity_id: lock.ti_ar_kaerell
  - service: climate.set_temperature
    data:
      entity_id: climate.radiateur_parents
      temperature: 18
  - service: climate.set_temperature
    data:
      entity_id: climate.radiateur_bureau
      temperature: 18
  - service: climate.set_temperature
    data:
      entity_id: climate.radiateur_salon
      temperature: 18
  