alias: Ferme le verrou quand la maison est vide
trigger:
  - platform: state
    entity_id: sensor.home
    to: empty
# condition:
#   - condition: state
#     entity_id: lock.ti_ar_kaerell
#     state: unlocked
action:
  - service: lock.lock
    data:
      entity_id: lock.ti_ar_kaerell
