alias: Download Snapshot Salon
initial_state: 'on'
trigger:
  - platform: mqtt
    topic: 'netatmo/update/salon'
action:
  - service: downloader.download_file
    data_template:
      { "url": "{{ trigger.payload_json['snapshot_url'] }}",
        "subdir": "camera",
        "filename": "CamSalon_{{ trigger.payload_json['event_type'] }}_{{ now().strftime('%Y-%m-%d-%H%M') }}.jpg",
        "overwrite": "true"
       }
  - service: downloader.download_file
    data_template:
      { "url": "{{ trigger.payload_json['snapshot_url'] }}",
        "subdir": "camera",
        "filename": "CamSalon_{{ trigger.payload_json['event_type'] }}_latest.jpg",
        "overwrite": "true"
      }
  - delay:
      seconds: 5
  - service: image_processing.scan
      entity_id: image_processing.face_counter_salon
