alias: Download Snapshot Terrasse
initial_state: 'on'
trigger:
  - platform: mqtt
    topic: 'netatmo/update/terrasse'
condition:
  - condition: template
    value_template: "{{ 'snapshot_url' in trigger.payload }}"
action:
  - service: downloader.download_file
    data_template:
      url: "{{ trigger.payload_json['snapshot_url'] }}"
      subdir: "camera"
      filename: "CamTerrasse_{{ trigger.payload_json['event_type'] }}_{{ now().strftime('%Y-%m-%d-%H%M') }}.jpg"
      overwrite: true
  - service: downloader.download_file
    data_template:
      url: "{{ trigger.payload_json['snapshot_url'] }}"
      subdir: "camera"
      filename: "CamTerrasse_{{ trigger.payload_json['event_type'] }}_latest.jpg"
      overwrite": true
  - service: downloader.download_file
    data_template:
      url: "{{ trigger.payload_json['snapshot_url'] }}"
      subdir: "camera"
      filename: "CamTerrasse_latest.jpg"
      overwrite: true
  - service: image_processing.scan
    data:
      entity_id: image_processing.face_counter_terrasse_human