alias: Download Snapshot Terrasse
initial_state: 'on'
trigger:
  - platform: mqtt
    topic: 'netatmo/update'
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['device_id'] == '70:ee:50:39:a5:a4' }}"
action:
  - service: mqtt.publish
    data_template:
      topic: netatmo/update/terrasse
      retain: true
      payload_template: >
        {{ trigger.payload_json | tojson }}
  - service: downloader.download_file
    data_template:
      { "url": "{{ trigger.payload_json['snapshot_url'] }}",
        "subdir": "camera",
        "filename": "CamTerrasse_{{ trigger.payload_json['event_type'] }}_{{ now().strftime('%Y-%m-%d-%H%M') }}.jpg",
        "overwrite": "true"
      }
  - service: downloader.download_file
    data_template:
      { "url": "{{ trigger.payload_json['snapshot_url'] }}",
        "subdir": "camera",
        "filename": "CamTerrasse_{{ trigger.payload_json['event_type'] }}_latest.jpg",
        "overwrite": "true"
      }
  - service: downloader.download_file
    data_template:
      { "url": "{{ trigger.payload_json['snapshot_url'] }}",
        "subdir": "camera",
        "filename": "CamTerrasse_latest.jpg",
        "overwrite": "true"
      }
  - delay:
      seconds: 5
  - service: image_processing.scan
    data:
      entity_id: image_processing.face_counter_terrasse