alias: Movement Detected
initial_state: 'on'
trigger:
  platform: webhook
#  webhook_id: netatmo_webhook
  webhook_id: 0139a42bd40897717441be1a14a6466879f4a1fc91ecaae9886605baa349ec46
action:
  - service: notify.webhook
    data_template:
      message: "WORKING - {{ now() }} - {{ trigger.webhook_id }}: {{ trigger.json | tojson }}"
  - service: mqtt.publish
    data_template:
      topic: netatmo/update
      retain: true
      payload_template: >
        {{ trigger.json | tojson }}
