alias: Log Unused Webhooks
initial_state: 'on'
trigger:
  - platform: webhook
    webhook_id: netatmo_alert
  - platform: webhook
    webhook_id: netatmo_webhook
  - platform: webhook
    webhook_id: netatmo_connect
action:
  - service: notify.webhook
    data_template:
      message: "{{ now() }} - {{ trigger.webhook_id }}: {{ trigger.json | tojson }}"