id: VincentEstSurLeRetour
alias: Vincent est sur le retour
trigger:
- platform: state
  to: towards
  entity_id: proximity.home1
action:
- service: notify.google_push_pixel_2
  data:
    message: "Vincent est sur le retour"