id: VirginiaEstSurLeRetour
alias: Virginia est sur le retour
trigger:
  platform: template
  value_template: '{{ states.proximity.home2.attributes.dir_of_travel == "towards" }}'
  for:
    minutes: 2
condition:
  condition: numeric_state
  entity_id: proximity.home2
  above: 50
action:
- service: notify.google_push_pixel_2
  data:
    message: "Virginia est sur le retour"