id: VirginiaEstSurLeRetour
alias: Virginia est sur le retour
trigger:
  platform: template
  value_template: '{{ states.proximity.home2.attributes.dir_of_travel == "towards" }}'
action:
- service: notify.google_push_pixel_2
  data:
    message: "Virginia est sur le retour"