alias: Ferme tout chez Lenaïc s'il fait trop chaud dehors
trigger:
  - platform: template
    value_template: '{{ (states.sensor.sensative_strips_comfort_temperature.state
    | float) < (states.sensor.netatmo_terrasse_temperature.state | float) }}'
condition:
  - condition: template
    value_template: "{{ (states.sensor.sensative_strips_comfort_temperature.state
    | float) > 21 }}"
  - condition: or
    conditions:
      - condition: state
        entity_id: cover.volet_lenaic
        state: open
      - condition: state
        entity_id: cover.velux_lenaic
        state: open
action:
  - service: script.turn_on
    data:
      entity_id: script.close_both_lenaic
